import Foundation

/// Advance preparation for one dish, as generated by the server.
///
/// "Prep" means only work that must happen *before* cook time — soaking,
/// marinating, fermenting, thawing, pre-boiling. Ordinary in-the-moment steps
/// (heat oil, temper spices) are excluded server-side; the recipe video covers those.
///
/// Mirrors `lib/prep-types.ts`. Category keys and `formatLeadTime` wording must
/// stay in step with the web app and Android.

/// The kinds of advance work. Keys match the server's `PREP_CATEGORIES` exactly.
public enum PrepCategory: String, CaseIterable, Sendable {
    case soak, marinate, ferment, thaw, boil, chop, rest

    public var key: String { rawValue }

    public var emoji: String {
        switch self {
        case .soak: "💧"
        case .marinate: "🧂"
        case .ferment: "🫙"
        case .thaw: "❄️"
        case .boil: "♨️"
        case .chop: "🔪"
        case .rest: "⏳"
        }
    }

    public static func fromKey(_ key: String) -> PrepCategory? { PrepCategory(rawValue: key) }
}

/// Tolerant codec: an unrecognised key decodes to `.rest` rather than throwing.
/// One new server-side category must not fail an entire week's response.
extension PrepCategory: Codable {
    public init(from decoder: any Decoder) throws {
        let raw = try decoder.singleValueContainer().decode(String.self)
        self = PrepCategory(rawValue: raw) ?? .rest
    }

    public func encode(to encoder: any Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}

public struct PrepStep: Codable, Hashable, Sendable {
    public var text: String
    /// How long before cook time this step has to start. Soaking chana is 480.
    public var leadTimeMinutes: Int
    public var category: PrepCategory

    public init(text: String = "", leadTimeMinutes: Int = 0, category: PrepCategory = .rest) {
        self.text = text
        self.leadTimeMinutes = leadTimeMinutes
        self.category = category
    }

    public init(from decoder: any Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        text = try c.decodeIfPresent(String.self, forKey: .text) ?? ""
        leadTimeMinutes = try c.decodeIfPresent(Int.self, forKey: .leadTimeMinutes) ?? 0
        category = try c.decodeIfPresent(PrepCategory.self, forKey: .category) ?? .rest
    }
}

public struct MealPrep: Codable, Hashable, Sendable {
    public var steps: [PrepStep]
    public var maxLeadTimeMinutes: Int
    /// Hands-on minutes for the advance prep only, not the cooking.
    public var activeMinutes: Int
    public var generatedAt: String?

    public init(
        steps: [PrepStep] = [],
        maxLeadTimeMinutes: Int = 0,
        activeMinutes: Int = 0,
        generatedAt: String? = nil
    ) {
        self.steps = steps
        self.maxLeadTimeMinutes = maxLeadTimeMinutes
        self.activeMinutes = activeMinutes
        self.generatedAt = generatedAt
    }

    public init(from decoder: any Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        steps = try c.decodeIfPresent([PrepStep].self, forKey: .steps) ?? []
        maxLeadTimeMinutes = try c.decodeIfPresent(Int.self, forKey: .maxLeadTimeMinutes) ?? 0
        activeMinutes = try c.decodeIfPresent(Int.self, forKey: .activeMinutes) ?? 0
        generatedAt = try c.decodeIfPresent(String.self, forKey: .generatedAt)
    }
}

/// Human-readable lead time, e.g. 480 → "8 hours ahead".
///
/// Port of `formatLeadTime` in `lib/prep-types.ts` — same branches, same wording,
/// so the app and the web app describe the same dish identically. Note the
/// rounding is `Math.round` on a *float division*, not integer division.
public func formatLeadTime(_ minutes: Int) -> String {
    if minutes <= 0 { return "Just before cooking" }
    if minutes < 60 { return "\(minutes) min ahead" }

    let hours = Int((Float(minutes) / 60).rounded())
    if hours < 24 { return "\(hours) \(hours == 1 ? "hour" : "hours") ahead" }

    let days = Int((Float(hours) / 24).rounded())
    return "\(days) \(days == 1 ? "day" : "days") ahead"
}
